export const FAMILIES=[
  {id:"hero",label:"Hero",description:"Iconic product authority"},
  {id:"reveal",label:"Reveal",description:"Progressive discovery"},
  {id:"motion",label:"Motion",description:"Camera and object energy"},
  {id:"detail",label:"Detail",description:"Material and feature focus"},
  {id:"tech",label:"Tech",description:"Engineered presentation"},
  {id:"graphic",label:"Graphic",description:"Designed composition"},
  {id:"closing",label:"Closing",description:"Resolve and final statement"}
];

const p=(id,family,title,duration,start,end,description)=>({id,family,title,duration,start,end,description});
export const PRESETS=[
  p("hero.silent-authority","hero","Silent Authority",72,{"subject.positionX":-.18,"subject.positionY":-.05,"subject.scale":.92,"subject.rotationY":-22,"camera.distance":5.5,"camera.height":.1,"light.key":.72,"environment.depth":.26},{"subject.positionX":.18,"subject.positionY":.04,"subject.scale":1.08,"subject.rotationY":18,"camera.distance":4.4,"camera.height":.18,"light.key":1.05,"environment.depth":.48},"Measured push with a controlled product turn."),
  p("hero.monument","hero","Monument",84,{"subject.positionX":0,"subject.positionY":-.12,"subject.scale":.78,"subject.rotationY":-8,"camera.distance":6.5,"camera.height":-.18,"light.key":.52,"environment.depth":.18},{"subject.positionX":0,"subject.positionY":.05,"subject.scale":1.22,"subject.rotationY":8,"camera.distance":4.2,"camera.height":-.06,"light.key":1.15,"environment.depth":.4},"Low-angle rise into an iconic final frame."),
  p("reveal.edge-light","reveal","Edge Light Reveal",64,{"subject.positionX":-.28,"subject.positionY":0,"subject.scale":.86,"subject.rotationY":-74,"camera.distance":5.8,"camera.height":.05,"light.key":.2,"environment.depth":.12},{"subject.positionX":.06,"subject.positionY":.02,"subject.scale":1.04,"subject.rotationY":-12,"camera.distance":4.7,"camera.height":.12,"light.key":1.35,"environment.depth":.52},"Starts almost unreadable and resolves through edge light."),
  p("reveal.parallax","reveal","Parallax Discovery",72,{"subject.positionX":-.65,"subject.positionY":-.03,"subject.scale":.82,"subject.rotationY":-46,"camera.distance":6.2,"camera.height":.2,"light.key":.62,"environment.depth":.62},{"subject.positionX":.12,"subject.positionY":.03,"subject.scale":1.02,"subject.rotationY":12,"camera.distance":4.8,"camera.height":.05,"light.key":1.02,"environment.depth":.3},"Travels from spatial obstruction into a clean product read."),
  p("motion.orbit","motion","Controlled Orbit",78,{"subject.positionX":-.12,"subject.positionY":0,"subject.scale":.9,"subject.rotationY":-68,"camera.distance":5.4,"camera.height":.12,"light.key":.82,"environment.depth":.4},{"subject.positionX":.12,"subject.positionY":.02,"subject.scale":1.04,"subject.rotationY":58,"camera.distance":4.8,"camera.height":.18,"light.key":1.0,"environment.depth":.46},"Wide readable rotation without losing silhouette."),
  p("motion.impact","motion","Impact Settle",48,{"subject.positionX":0,"subject.positionY":.28,"subject.scale":1.28,"subject.rotationY":-28,"camera.distance":4.1,"camera.height":.3,"light.key":1.45,"environment.depth":.7},{"subject.positionX":0,"subject.positionY":0,"subject.scale":1,"subject.rotationY":0,"camera.distance":4.9,"camera.height":.08,"light.key":.88,"environment.depth":.34},"Fast arrival followed by a composed settle."),
  p("detail.material","detail","Material Glide",68,{"subject.positionX":-.5,"subject.positionY":.12,"subject.scale":1.32,"subject.rotationY":-22,"camera.distance":3.65,"camera.height":.28,"light.key":.9,"environment.depth":.22},{"subject.positionX":.52,"subject.positionY":-.04,"subject.scale":1.48,"subject.rotationY":18,"camera.distance":3.2,"camera.height":.12,"light.key":1.22,"environment.depth":.3},"Macro lateral glide for surface and edge response."),
  p("detail.signature","detail","Signature Feature",60,{"subject.positionX":.32,"subject.positionY":-.18,"subject.scale":1.18,"subject.rotationY":42,"camera.distance":4.1,"camera.height":-.12,"light.key":.72,"environment.depth":.24},{"subject.positionX":-.12,"subject.positionY":.12,"subject.scale":1.5,"subject.rotationY":16,"camera.distance":3.35,"camera.height":.18,"light.key":1.25,"environment.depth":.38},"Moves attention toward one defining feature."),
  p("tech.scan","tech","Scan Pass",72,{"subject.positionX":0,"subject.positionY":-.16,"subject.scale":.86,"subject.rotationY":-32,"camera.distance":5.9,"camera.height":.22,"light.key":.38,"environment.depth":.72},{"subject.positionX":0,"subject.positionY":.06,"subject.scale":1.08,"subject.rotationY":24,"camera.distance":4.8,"camera.height":.02,"light.key":1.4,"environment.depth":.82},"Technical reveal with stronger atmosphere and light progression."),
  p("tech.proof","tech","Engineering Proof",84,{"subject.positionX":-.2,"subject.positionY":0,"subject.scale":.82,"subject.rotationY":-12,"camera.distance":6.4,"camera.height":.38,"light.key":.72,"environment.depth":.5},{"subject.positionX":.18,"subject.positionY":0,"subject.scale":1.16,"subject.rotationY":52,"camera.distance":4.6,"camera.height":.14,"light.key":1.08,"environment.depth":.62},"Clear volumetric proof with a restrained camera path."),
  p("graphic.diagonal","graphic","Graphic Diagonal",56,{"subject.positionX":-.72,"subject.positionY":.28,"subject.scale":.72,"subject.rotationY":-38,"camera.distance":6.1,"camera.height":.42,"light.key":.78,"environment.depth":.3},{"subject.positionX":.48,"subject.positionY":-.22,"subject.scale":1.12,"subject.rotationY":18,"camera.distance":4.7,"camera.height":-.12,"light.key":1.08,"environment.depth":.48},"Designed diagonal movement with intentional negative space."),
  p("graphic.poster","graphic","Poster Hold",72,{"subject.positionX":.55,"subject.positionY":-.08,"subject.scale":.84,"subject.rotationY":-18,"camera.distance":5.8,"camera.height":.04,"light.key":.8,"environment.depth":.22},{"subject.positionX":.3,"subject.positionY":.02,"subject.scale":1.02,"subject.rotationY":8,"camera.distance":5.1,"camera.height":.08,"light.key":1.04,"environment.depth":.34},"Leaves a clean copy field while the product settles."),
  p("closing.resolve","closing","Final Resolve",72,{"subject.positionX":-.2,"subject.positionY":.06,"subject.scale":1.12,"subject.rotationY":38,"camera.distance":4.5,"camera.height":.18,"light.key":1.12,"environment.depth":.46},{"subject.positionX":0,"subject.positionY":0,"subject.scale":.96,"subject.rotationY":0,"camera.distance":5.2,"camera.height":.05,"light.key":.84,"environment.depth":.26},"Returns energy to a balanced final product statement."),
  p("closing.monogram","closing","Brand Hold",96,{"subject.positionX":.22,"subject.positionY":0,"subject.scale":1.04,"subject.rotationY":18,"camera.distance":4.8,"camera.height":.1,"light.key":1.0,"environment.depth":.38},{"subject.positionX":.34,"subject.positionY":0,"subject.scale":.92,"subject.rotationY":0,"camera.distance":5.5,"camera.height":.05,"light.key":.74,"environment.depth":.18},"Slowly opens a protected area for brand or typography."),
];
export const PRESET_MAP=new Map(PRESETS.map(preset=>[preset.id,preset]));
export function presetsForFamily(family){return PRESETS.filter(preset=>preset.family===family);}
