import {clamp} from "../core/utils.js";

class CanvasFallback{
  constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext("2d");this.resizeObserver=null;this.mount();}
  mount(){const resize=()=>{const rect=this.canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);this.canvas.width=Math.max(1,Math.round(rect.width*dpr));this.canvas.height=Math.max(1,Math.round(rect.height*dpr));this.ctx.setTransform(dpr,0,0,dpr,0,0);};this.resizeObserver=new ResizeObserver(resize);this.resizeObserver.observe(this.canvas);resize();}
  render(frame,state){const {ctx,canvas}=this,w=canvas.clientWidth,h=canvas.clientHeight,v=frame?.values||{};ctx.clearRect(0,0,w,h);const depth=clamp(v["environment.depth"]??.3,0,1),gradient=ctx.createRadialGradient(w*.52,h*.43,0,w*.52,h*.43,Math.max(w,h)*.7);gradient.addColorStop(0,`rgba(${26+Math.round(depth*20)},${27+Math.round(depth*10)},${34+Math.round(depth*12)},1)`);gradient.addColorStop(1,"#030304");ctx.fillStyle=gradient;ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(w*.5+(v["subject.positionX"]??0)*w*.12,h*.53-(v["subject.positionY"]??0)*h*.12);const scale=(v["subject.scale"]??1)*Math.min(w,h)*.20,rot=(v["subject.rotationY"]??0)*Math.PI/180;ctx.rotate(rot*.22);ctx.shadowColor="rgba(255,121,80,.2)";ctx.shadowBlur=30;const g=ctx.createLinearGradient(-scale,0,scale,0);g.addColorStop(0,"#0c0d10");g.addColorStop(.42,"#d4d7dc");g.addColorStop(.56,"#5d626a");g.addColorStop(1,"#111216");ctx.fillStyle=g;roundRect(ctx,-scale*.85,-scale*.14,scale*1.7,scale*.28,scale*.14);ctx.fill();ctx.restore();}
  dispose(){this.resizeObserver?.disconnect();}
}
function roundRect(ctx,x,y,w,h,r){const rr=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+rr,y);ctx.arcTo(x+w,y,x+w,y+h,rr);ctx.arcTo(x+w,y+h,x,y+h,rr);ctx.arcTo(x,y+h,x,y,rr);ctx.arcTo(x,y,x+w,y,rr);ctx.closePath();}
const rad=value=>Number(value||0)*Math.PI/180;
const vec=(value,fallback=[0,0,0])=>Array.isArray(value)?value:fallback;

export class RendererService{
  constructor({canvas,onStatus,persistence,workspace="render",forceFallback=false}){
    this.canvas=canvas;this.onStatus=onStatus;this.persistence=persistence;this.workspace=workspace;this.forceFallback=forceFallback;this.mode="booting";this.resizeObserver=null;this.fallback=null;this.assetRevision="";this.loadedAssets=new Map();this.loadingAssets=new Map();this.viewportCallbacks={};this.viewportCameraMode="editor";this.viewportActive=workspace==="viewport";this.transformDragging=false;this.lastState=null;this.ready=this.init();
  }
  status(label,mode="ready",detail=""){this.mode=mode;this.onStatus?.({label,mode,detail});}
  async init(){
    try{
      if(this.forceFallback)throw new Error("Forced fallback");
      if(globalThis.location?.protocol==="file:")throw new Error("Static file preview uses Canvas fallback");
      const [T,gltfModule,rgbeModule,orbitModule,transformModule,dracoModule,meshoptModule]=await Promise.race([
        Promise.all([import("three"),import("three/addons/loaders/GLTFLoader.js"),import("three/addons/loaders/RGBELoader.js"),import("three/addons/controls/OrbitControls.js"),import("three/addons/controls/TransformControls.js"),import("three/addons/loaders/DRACOLoader.js"),import("three/addons/libs/meshopt_decoder.module.js")]),
        new Promise((_,reject)=>setTimeout(()=>reject(new Error("Three.js modules timed out")),9000))
      ]);
      this.T=T;this.GLTFLoader=gltfModule.GLTFLoader;this.RGBELoader=rgbeModule.RGBELoader;this.OrbitControls=orbitModule.OrbitControls;this.TransformControls=transformModule.TransformControls;this.DRACOLoader=dracoModule.DRACOLoader;this.MeshoptDecoder=meshoptModule.MeshoptDecoder;this.initThree();this.status("THREE · V43B.2 READY","ready");
    }catch(error){console.warn("V43B.2 Three.js unavailable, using visible fallback",error);this.fallback=new CanvasFallback(this.canvas);this.status("PROXY · FALLBACK","fallback",String(error?.message||error));}
  }
  initThree(){
    const T=this.T;
    this.renderer=new T.WebGLRenderer({canvas:this.canvas,antialias:true,alpha:false,powerPreference:"high-performance",preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));this.renderer.setClearColor(0x040405,1);this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;
    this.scene=new T.Scene();this.scene.background=new T.Color(0x050506);this.scene.fog=new T.FogExp2(0x050506,.026);this.studioEnvironment=this.createStudioEnvironment();this.scene.environment=this.studioEnvironment;
    this.shotCamera=new T.PerspectiveCamera(38,1,.02,1000);this.shotCamera.name="SHOT_CAMERA";
    this.editorCamera=new T.PerspectiveCamera(45,1,.02,2000);this.editorCamera.name="EDITOR_CAMERA";this.editorCamera.position.set(5.8,3.5,7.4);
    this.nodeGroups=new Map();this.contentGroups=new Map();this.assetObjects=new Map();this.autoTransforms=new Map();
    this.heroGroup=this.createNodeGroup("hero-proxy","hero");this.environmentGroup=this.createNodeGroup("environment-proxy","environment");this.propsRoot=new T.Group();this.propsRoot.name="PROPS";this.scene.add(this.propsRoot);
    this.proxy=this.createProxy();this.contentGroups.get("hero-proxy").add(this.proxy);this.assetObjects.set("hero-proxy",this.proxy);this.autoTransforms.set("hero-proxy",{scale:1,center:[0,0,0],ground:0,radius:1.35,size:[2.7,.7,.9]});
    this.floor=new T.Mesh(new T.PlaneGeometry(80,80),new T.MeshPhysicalMaterial({color:0x09090b,roughness:.62,metalness:.22}));this.floor.rotation.x=-Math.PI/2;this.floor.position.y=-1.05;this.floor.receiveShadow=true;this.environmentGroup.content.add(this.floor);
    this.grid=new T.GridHelper(40,80,0x303038,0x18181d);this.grid.position.y=-1.045;this.grid.material.transparent=true;this.grid.material.opacity=.36;this.scene.add(this.grid);
    this.ambient=new T.HemisphereLight(0x394052,0x050506,.48);this.key=new T.DirectionalLight(0xf2f4ff,2.1);this.key.position.set(-3,4,5);this.key.castShadow=true;this.key.shadow.mapSize.set(1024,1024);this.rim=new T.PointLight(0xff7950,5.2,28,1.6);this.rim.position.set(3,1.4,-1);this.fill=new T.PointLight(0x4b78ff,1.1,18,2);this.fill.position.set(-2,-.4,2);this.scene.add(this.ambient,this.key,this.rim,this.fill);
    const points=[];for(let i=0;i<100;i++)points.push((Math.random()-.5)*18,Math.random()*8-2.2,-Math.random()*12-1);const geometry=new T.BufferGeometry();geometry.setAttribute("position",new T.Float32BufferAttribute(points,3));this.motes=new T.Points(geometry,new T.PointsMaterial({color:0xffa07c,size:.035,transparent:true,opacity:.25,depthWrite:false}));this.scene.add(this.motes);
    this.shotCameraHelper=new T.CameraHelper(this.shotCamera);this.shotCameraHelper.visible=false;this.scene.add(this.shotCameraHelper);this.keyHelper=new T.DirectionalLightHelper(this.key,.45,0xff7950);this.keyHelper.visible=false;this.scene.add(this.keyHelper);this.selectionHelper=new T.BoxHelper(this.heroGroup.creative,0x59d7df);this.selectionHelper.visible=false;this.scene.add(this.selectionHelper);
    this.pmrem=new T.PMREMGenerator(this.renderer);this.pmrem.compileEquirectangularShader();this.hdriTexture=null;this.hdriTarget=null;
    this.setupViewportControls();
    const resize=()=>{const rect=this.canvas.getBoundingClientRect();if(!rect.width||!rect.height)return;this.renderer.setSize(rect.width,rect.height,false);this.shotCamera.aspect=rect.width/rect.height;this.shotCamera.updateProjectionMatrix();this.editorCamera.aspect=rect.width/rect.height;this.editorCamera.updateProjectionMatrix();};this.resizeObserver=new ResizeObserver(resize);this.resizeObserver.observe(this.canvas);resize();
    this.canvas.addEventListener("webglcontextlost",event=>{event.preventDefault();this.status("CONTEXT · LOST","error");});this.canvas.addEventListener("webglcontextrestored",()=>this.status("THREE · RESTORED","ready"));
  }

  createStudioEnvironment(){
    const T=this.T;try{const faces=[];for(let i=0;i<6;i++){const canvas=document.createElement("canvas");canvas.width=canvas.height=64;const ctx=canvas.getContext("2d"),bg=ctx.createLinearGradient(0,0,64,64);bg.addColorStop(0,"#08090b");bg.addColorStop(.52,"#252a31");bg.addColorStop(1,"#050506");ctx.fillStyle=bg;ctx.fillRect(0,0,64,64);const strip=ctx.createLinearGradient(0,0,64,0);strip.addColorStop(0,"rgba(255,255,255,0)");strip.addColorStop(.42,"rgba(255,245,238,.06)");strip.addColorStop(.5,"rgba(255,245,238,.82)");strip.addColorStop(.58,"rgba(255,121,80,.18)");strip.addColorStop(1,"rgba(255,255,255,0)");ctx.fillStyle=strip;ctx.fillRect(0,0,64,64);faces.push(canvas);}const texture=new T.CubeTexture(faces);texture.colorSpace=T.SRGBColorSpace;texture.needsUpdate=true;return texture;}catch(error){console.warn("Studio environment unavailable",error);return null;}
  }
  createProxy(){const T=this.T,group=new T.Group(),bodyMat=new T.MeshPhysicalMaterial({color:0x34373d,metalness:.72,roughness:.27,clearcoat:.5,clearcoatRoughness:.35}),darkMat=new T.MeshStandardMaterial({color:0x090a0c,metalness:.45,roughness:.5}),body=new T.Mesh(new T.BoxGeometry(2.35,.34,.48,6,2,3),bodyMat),handle=new T.Mesh(new T.BoxGeometry(.52,.58,.7,3,3,3),darkMat),detail=new T.Mesh(new T.TorusGeometry(.18,.035,12,32),new T.MeshPhysicalMaterial({color:0xff7950,emissive:0x401208,emissiveIntensity:.55,metalness:.5,roughness:.3}));body.rotation.z=-.05;handle.position.x=-1.23;handle.rotation.z=-.05;detail.rotation.y=Math.PI/2;detail.position.set(-.98,0,.36);for(const mesh of [body,handle,detail]){mesh.castShadow=true;mesh.receiveShadow=true;}group.add(body,handle,detail);group.name="CALIBRATED_PROXY";return group;}
  createNodeGroup(id,type){const T=this.T,creative=new T.Group(),correction=new T.Group(),auto=new T.Group(),content=new T.Group();creative.name=`${id}:creative`;correction.name=`${id}:correction`;auto.name=`${id}:auto`;content.name=`${id}:content`;creative.add(correction);correction.add(auto);auto.add(content);creative.userData={nodeId:id,nodeType:type};creative.correction=correction;creative.auto=auto;creative.content=content;this.scene.add(creative);this.nodeGroups.set(id,creative);this.contentGroups.set(id,content);return creative;}
  setupViewportControls(){
    if(!["viewport","timeline"].includes(this.workspace))return;
    this.orbit=new this.OrbitControls(this.editorCamera,this.canvas);this.orbit.enableDamping=true;this.orbit.dampingFactor=.08;this.orbit.target.set(0,0,0);this.orbit.minDistance=.08;this.orbit.maxDistance=500;
    this.orbit.addEventListener("start",()=>this.viewportCallbacks.onCameraStart?.());this.orbit.addEventListener("change",()=>{if(!this.orbit.enabled||this.suppressCameraCallback)return;this.viewportCallbacks.onCameraChange?.({position:this.editorCamera.position.toArray(),target:this.orbit.target.toArray(),fov:this.editorCamera.fov});});this.orbit.addEventListener("end",()=>this.viewportCallbacks.onCameraEnd?.());
    if(this.workspace!=="viewport")return;
    this.transformControl=new this.TransformControls(this.editorCamera,this.canvas);this.transformControl.setSize(.8);this.transformHelper=this.transformControl.getHelper?this.transformControl.getHelper():this.transformControl;this.scene.add(this.transformHelper);this.transformControl.addEventListener("dragging-changed",event=>{this.transformDragging=event.value;if(this.orbit)this.orbit.enabled=!event.value;event.value?this.viewportCallbacks.onTransformStart?.():this.viewportCallbacks.onTransformEnd?.();});this.transformControl.addEventListener("objectChange",()=>{const object=this.transformControl.object;if(!object)return;this.viewportCallbacks.onTransformChange?.({nodeId:object.userData.nodeId,position:object.position.toArray(),rotation:[object.rotation.x,object.rotation.y,object.rotation.z],scale:object.scale.toArray()});});
  }
  configureViewport({nodeId,tool,cameraMode,active=true,onTransformStart,onTransformChange,onTransformEnd,onCameraStart,onCameraChange,onCameraEnd}={}){
    this.viewportCallbacks={onTransformStart,onTransformChange,onTransformEnd,onCameraStart,onCameraChange,onCameraEnd};this.viewportCameraMode=cameraMode==="shot"?"shot":"editor";this.viewportActive=active!==false;
    if(this.orbit)this.orbit.enabled=this.viewportActive&&this.viewportCameraMode!=="shot"&&!this.transformDragging;
    if(!this.transformControl)return;const object=this.nodeGroups.get(nodeId);if(this.viewportActive&&object&&!["camera-main","camera-editor","light-default"].includes(nodeId)){this.transformControl.attach(object);this.transformControl.setMode(tool==="rotate"?"rotate":tool==="scale"?"scale":"translate");if(this.transformHelper)this.transformHelper.visible=this.viewportCameraMode==="editor";}else this.transformControl.detach();
  }
  setEditorCamera(camera){if(!camera||!this.editorCamera||this.transformDragging)return;const p=vec(camera.position,[5.8,3.5,7.4]),t=vec(camera.target,[0,0,0]);this.suppressCameraCallback=true;this.editorCamera.position.fromArray(p);this.editorCamera.fov=Number(camera.fov)||45;this.editorCamera.updateProjectionMatrix();if(this.orbit){this.orbit.target.fromArray(t);this.orbit.update();}this.suppressCameraCallback=false;}
  frameNode(nodeId="hero-proxy",all=false){if(!this.T||!this.editorCamera)return;const T=this.T,objects=all?[...this.nodeGroups.values()].filter(o=>o.visible):[this.nodeGroups.get(nodeId)].filter(Boolean),box=new T.Box3();for(const object of objects)box.expandByObject(object,true);if(box.isEmpty())return;const sphere=box.getBoundingSphere(new T.Sphere()),distance=Math.max(.25,sphere.radius/Math.sin(rad(this.editorCamera.fov*.5))*1.25),direction=new T.Vector3(1,.65,1).normalize();this.editorCamera.position.copy(sphere.center).addScaledVector(direction,distance);if(this.orbit){this.orbit.target.copy(sphere.center);this.orbit.update();}this.viewportCallbacks.onCameraChange?.({position:this.editorCamera.position.toArray(),target:sphere.center.toArray(),fov:this.editorCamera.fov});this.viewportCallbacks.onCameraEnd?.();}
  async syncAssets(state){
    if(!this.T||!this.persistence)return;
    const ids=[state.assets.heroId,state.assets.environmentId,...(state.assets.secondaryIds||[]),state.assets.hdriId].filter(Boolean),revision=ids.map(id=>`${id}:${state.assets.byId[id]?.updatedAt||state.assets.byId[id]?.status||""}`).join("|");if(revision===this.assetRevision)return;this.assetRevision=revision;
    for(const [id,record] of [...this.loadedAssets])if(!ids.includes(id)&&record.kind!=="builtin")this.unloadAsset(id);
    await Promise.all(ids.map(id=>this.ensureAsset(id,state.assets.byId[id],state).catch(error=>{console.error("Asset load failed",id,error);this.status(`ASSET ERROR · ${state.assets.byId[id]?.name||id}`,"error",String(error?.message||error));})));
  }
  async ensureAsset(id,meta,state){if(!id||!meta||meta.source==="builtin"||this.loadedAssets.has(id))return;if(this.loadingAssets.has(id))return this.loadingAssets.get(id);const promise=this.loadAsset(id,meta,state).finally(()=>this.loadingAssets.delete(id));this.loadingAssets.set(id,promise);return promise;}
  async loadAsset(id,meta,state){
    const record=await this.persistence.getAsset(id);if(!record?.blob)throw new Error("Binary data missing from IndexedDB");this.status(`LOADING · ${meta.name||record.name}`,"loading");
    if(meta.type==="hdri"){await this.loadHDRI(id,record,meta);this.status(`HDRI · ${meta.name||record.name}`,"ready");return;}
    const buffer=await record.blob.arrayBuffer(),loader=new this.GLTFLoader(),draco=new this.DRACOLoader();draco.setDecoderPath("https://www.gstatic.com/draco/versioned/decoders/1.5.7/");loader.setDRACOLoader(draco);if(this.MeshoptDecoder)loader.setMeshoptDecoder(this.MeshoptDecoder);const gltf=await new Promise((resolve,reject)=>loader.parse(buffer,"",resolve,reject));draco.dispose();const root=gltf.scene||gltf.scenes?.[0];if(!root)throw new Error("GLB contains no scene");this.prepareImported(root);const kind=meta.type,nodeId=kind==="hero"?"hero-proxy":kind==="environment"?"environment-proxy":meta.nodeId||`prop-${id}`;let group=this.nodeGroups.get(nodeId);if(!group){group=this.createNodeGroup(nodeId,"prop");this.propsRoot.add(group);}
    const content=this.contentGroups.get(nodeId);while(content.children.length){const old=content.children[0];content.remove(old);if(old!==this.proxy&&old!==this.floor)this.disposeObject(old);}content.add(root);const target=kind==="environment"?18:kind==="prop"?1.25:2.2,auto=this.computeAutoTransform(root,target,kind!=="environment");this.autoTransforms.set(nodeId,auto);this.assetObjects.set(id,root);let mixer=null,duration=0;if(gltf.animations?.length){mixer=new this.T.AnimationMixer(root);for(const clip of gltf.animations){mixer.clipAction(clip).play();duration=Math.max(duration,clip.duration||0);}}this.loadedAssets.set(id,{id,nodeId,kind,root,animations:gltf.animations||[],mixer,duration,auto});this.applyAutoTransform(nodeId,state.scene.nodes[nodeId]);if(["viewport","timeline"].includes(this.workspace)&&state.ui.selectedNodeId===nodeId)this.configureViewport({nodeId,tool:state.ui.viewportTool,cameraMode:state.scene.viewportCameraMode,...this.viewportCallbacks});this.status(`${kind.toUpperCase()} · ${meta.name||record.name}`,"ready");}
  prepareImported(root){const remove=[];root.traverse(object=>{if(object.isLight||object.isCamera){remove.push(object);return;}if(!object.isMesh)return;object.castShadow=true;object.receiveShadow=true;object.frustumCulled=true;for(const material of (Array.isArray(object.material)?object.material:[object.material]).filter(Boolean)){if(material.map)material.map.colorSpace=this.T.SRGBColorSpace;if(material.emissiveMap)material.emissiveMap.colorSpace=this.T.SRGBColorSpace;if("envMapIntensity" in material)material.envMapIntensity=Math.max(.7,Number(material.envMapIntensity)||0);if(material.transparent&&material.opacity>=.995){material.transparent=false;material.depthWrite=true;}material.needsUpdate=true;}});for(const object of remove)object.parent?.remove(object);}
  computeAutoTransform(root,target=2,ground=true){const T=this.T;root.updateMatrixWorld(true);const box=new T.Box3().setFromObject(root,true),size=box.getSize(new T.Vector3()),center=box.getCenter(new T.Vector3()),max=Math.max(size.x,size.y,size.z,.00001),scale=target/max;const scaledMinY=(box.min.y-center.y)*scale;return {scale,center:center.toArray(),ground:ground?-scaledMinY:0,radius:box.getBoundingSphere(new T.Sphere()).radius*scale,size:size.toArray().map(n=>n*scale)};}
  applyAutoTransform(nodeId,node){const group=this.nodeGroups.get(nodeId),auto=this.autoTransforms.get(nodeId);if(!group||!auto)return;const correction=node?.correction||{},enabled=correction.autoNormalize!==false,autoScale=enabled?auto.scale:1,center=enabled?auto.center:[0,0,0],ground=correction.autoGround!==false?auto.ground:0;group.auto.scale.setScalar(autoScale);group.auto.position.set(-center[0]*autoScale,ground-center[1]*autoScale, -center[2]*autoScale);}
  async loadHDRI(id,record,meta){const url=URL.createObjectURL(record.blob);try{const texture=await new this.RGBELoader().loadAsync(url);texture.mapping=this.T.EquirectangularReflectionMapping;if(this.hdriTarget)this.hdriTarget.dispose();if(this.hdriTexture)this.hdriTexture.dispose();this.hdriTexture=texture;this.hdriTarget=this.pmrem.fromEquirectangular(texture);this.scene.environment=this.hdriTarget.texture;this.loadedAssets.set(id,{id,kind:"hdri",texture});}finally{URL.revokeObjectURL(url);}}
  unloadAsset(id){const loaded=this.loadedAssets.get(id);if(!loaded)return;if(loaded.kind==="hdri"){this.hdriTarget?.dispose();this.hdriTexture?.dispose();this.hdriTarget=null;this.hdriTexture=null;this.scene.environment=this.studioEnvironment;}else{const content=this.contentGroups.get(loaded.nodeId);if(content){while(content.children.length){const old=content.children[0];content.remove(old);if(old!==this.proxy&&old!==this.floor)this.disposeObject(old);}}if(loaded.nodeId==="hero-proxy")content.add(this.proxy);else if(loaded.nodeId==="environment-proxy")content.add(this.floor);else{const group=this.nodeGroups.get(loaded.nodeId);group?.parent?.remove(group);this.nodeGroups.delete(loaded.nodeId);this.contentGroups.delete(loaded.nodeId);}this.assetObjects.delete(id);}this.loadedAssets.delete(id);}
  disposeObject(root){if(!root)return;root.traverse?.(object=>{if(object.geometry)object.geometry.dispose?.();for(const material of (Array.isArray(object.material)?object.material:[object.material]).filter(Boolean)){for(const key of ["map","normalMap","roughnessMap","metalnessMap","aoMap","emissiveMap","alphaMap"])material[key]?.dispose?.();material.dispose?.();}});}
  applyNodeState(nodeId,node,frameValues={}){const group=this.nodeGroups.get(nodeId);if(!group||!node)return;group.visible=node.visible!==false;const base=node.baseTransform||{},p=vec(base.position),r=vec(base.rotation),s=vec(base.scale,[1,1,1]);if(node.type==="hero"){group.position.set(p[0]+(frameValues["subject.positionX"]||0),p[1]+(frameValues["subject.positionY"]||0),p[2]+(frameValues["subject.positionZ"]||0));group.rotation.set(r[0]+rad(frameValues["subject.rotationX"]),r[1]+rad(frameValues["subject.rotationY"]),r[2]+rad(frameValues["subject.rotationZ"]));const uniform=frameValues["subject.scale"]??1;group.scale.set(s[0]*uniform,s[1]*uniform,s[2]*uniform);}else{group.position.fromArray(p);group.rotation.set(...r);group.scale.fromArray(s);}const c=node.correction||{},pivot=vec(c.pivot),cr=vec(c.rotation),cs=vec(c.scale,[1,1,1]);group.correction.position.set(-pivot[0],-pivot[1]+(Number(c.groundOffset)||0),-pivot[2]);group.correction.rotation.set(...cr);group.correction.scale.fromArray(cs);this.applyAutoTransform(nodeId,node);}
  applyState(frame,state,wallTime=0,{forceShotCamera=false}={}){
    const T=this.T,v=frame?.values||{};this.lastState=state;for(const loaded of this.loadedAssets.values())if(loaded.mixer)loaded.mixer.setTime(loaded.duration>0?wallTime%loaded.duration:wallTime);
    for(const [id,node] of Object.entries(state.scene.nodes||{}))if(this.nodeGroups.has(id))this.applyNodeState(id,node,v);
    const hero=this.nodeGroups.get("hero-proxy"),heroPosition=hero?.position||new T.Vector3(),bounds=this.autoTransforms.get("hero-proxy")||{radius:1.35};
    const fov=clamp(v["camera.fov"]??38,8,100),safeRadius=Math.max(.05,bounds.radius*(v["subject.scale"]??1)),fit=safeRadius/Math.tan(rad(fov*.5))*1.12,distance=Math.max(v["camera.distance"]??5.5,fit),height=v["camera.height"]??.1,target=new T.Vector3(heroPosition.x+(v["camera.targetX"]||0),heroPosition.y+(v["camera.targetY"]||0),heroPosition.z);
    this.shotCamera.fov=fov;this.shotCamera.position.set(target.x,height+heroPosition.y,target.z+distance);this.shotCamera.near=Math.max(.01,(distance-safeRadius)*.08);this.shotCamera.far=Math.max(100,distance+safeRadius*20);this.shotCamera.lookAt(target);this.shotCamera.updateProjectionMatrix();
    const key=v["light.key"]??.8;this.key.intensity=1.2+key*1.4;this.rim.intensity=2.8+key*3.1;this.ambient.intensity=.28+key*.2;
    const depth=clamp(v["environment.depth"]??.3,0,1);this.scene.fog.density=.008+depth*.04;this.grid.material.opacity=.12+depth*.22;this.scene.background?.setRGB?.(.018+depth*.012,.018+depth*.010,.024+depth*.015);this.motes.rotation.y=wallTime*.012;this.motes.position.x=Math.sin(wallTime*.09)*.08;
    const env=state.scene.environment||{};if(this.hdriTexture){this.scene.environment=this.hdriTarget?.texture||null;this.scene.background=env.backgroundVisible?this.hdriTexture:new T.Color(0x050506);if("environmentIntensity" in this.scene)this.scene.environmentIntensity=Number(env.intensity)||1;if("environmentRotation" in this.scene)this.scene.environmentRotation.set(0,rad(env.rotation||0),0);if("backgroundRotation" in this.scene)this.scene.backgroundRotation.set(0,rad(env.rotation||0),0);if("backgroundBlurriness" in this.scene)this.scene.backgroundBlurriness=clamp(Number(env.blur)||0,0,1);}else if(!(this.scene.background?.isColor))this.scene.background=new T.Color(0x050506);
    this.renderer.toneMappingExposure=Number(state.scene.rendererSettings?.exposure)||1;
    const viewport=(this.workspace==="viewport"||(this.workspace==="timeline"&&this.viewportActive))&&!forceShotCamera,camera=viewport&&this.viewportCameraMode!=="shot"?this.editorCamera:this.shotCamera;this.grid.visible=viewport&&state.scene.showGrid!==false;const helpers=viewport&&state.scene.showHelpers!==false&&this.viewportCameraMode!=="shot";this.shotCameraHelper.visible=helpers;this.keyHelper.visible=helpers;this.selectionHelper.visible=helpers;this.transformHelper&&(this.transformHelper.visible=helpers&&!!this.transformControl?.object);if(this.orbit){this.orbit.enabled=viewport&&this.viewportCameraMode!=="shot"&&!this.transformDragging;this.orbit.update();}
    if(this.selectionHelper.visible){const selected=this.nodeGroups.get(state.ui.selectedNodeId)||hero;this.selectionHelper.setFromObject(selected);this.selectionHelper.material.color.set(state.ui.selectedNodeId==="hero-proxy"?0x59d7df:0xff7950);}
    this.shotCameraHelper.update();this.keyHelper.update();return camera;
  }
  async render(frame,state,wallTime=0){await this.ready;if(this.fallback){this.fallback.render(frame,state);return;}if(!this.renderer||!frame)return;this.syncAssets(state);const camera=this.applyState(frame,state,wallTime);this.renderer.render(this.scene,camera);}
  async captureToCanvas(frame,state,targetCanvas,wallTime=0){await this.ready;if(!targetCanvas)return;if(this.fallback){const fallback=new CanvasFallback(targetCanvas);fallback.render(frame,state);fallback.dispose();return;}await this.syncAssets(state);const camera=this.applyState(frame,state,wallTime,{forceShotCamera:true});this.renderer.render(this.scene,camera);const ctx=targetCanvas.getContext("2d"),rect=targetCanvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.round(rect.width*dpr)),h=Math.max(1,Math.round(rect.height*dpr));if(targetCanvas.width!==w||targetCanvas.height!==h){targetCanvas.width=w;targetCanvas.height=h;}ctx.clearRect(0,0,w,h);ctx.drawImage(this.canvas,0,0,this.canvas.width,this.canvas.height,0,0,w,h);}
  dispose(){this.resizeObserver?.disconnect();this.orbit?.dispose();this.transformControl?.dispose();this.pmrem?.dispose();this.studioEnvironment?.dispose?.();this.renderer?.dispose();this.fallback?.dispose();for(const id of [...this.loadedAssets.keys()])this.unloadAsset(id);}
}
