import {AXIS_MAP,AXES,TRACKS,createDefaultState,DEFAULT_TRANSFORM,DEFAULT_TRANSFORM_LOCKS,correctionDefaultsForType} from "./default-state.js";
import {PRESET_MAP} from "../shots/presets.js";
import {SEQUENCE_PRESET_MAP} from "../shots/sequence-presets.js";
import {CREATIVE_AXIS_MAP,CREATIVE_AXES,defaultCreativeChoices,optionFor} from "../shots/creative-axes.js";
import {clamp,deepClone,seeded,uid} from "./utils.js";

function activeShot(state){return state.shots.byId[state.shots.activeShotId];}
function exclusionKey(axisId,optionId){return `${axisId}:${optionId}`;}
function ensureCreativeState(shot){
  shot.start.choices??=defaultCreativeChoices("start");shot.end.choices??=defaultCreativeChoices("end");
  shot.creativeLocks??=Object.fromEntries(CREATIVE_AXES.map(axis=>[axis.id,false]));shot.creativeExclusions??={};
}
function allowedCreativeOptions(shot,axis){ensureCreativeState(shot);return axis.options.filter(option=>!shot.creativeExclusions[exclusionKey(axis.id,option.id)]);}
function syncNumericLocksFromCreativeLocks(shot){
  shot.locks??=Object.fromEntries(AXES.map(axis=>[axis.id,false]));for(const axis of AXES)shot.locks[axis.id]=false;
  for(const creativeAxis of CREATIVE_AXES){if(!shot.creativeLocks?.[creativeAxis.id])continue;for(const numericAxisId of creativeAxis.advancedAxes||[])shot.locks[numericAxisId]=true;}
}
function applyAxisMutable(state,axisId,value,scope=state.ui.editScope){
  const axis=AXIS_MAP.get(axisId);if(!axis)return;const numeric=clamp(Number(value),axis.min,axis.max),shot=activeShot(state);
  if(scope==="start"||scope==="both")shot.start.values[axisId]=numeric;if(scope==="end"||scope==="both")shot.end.values[axisId]=numeric;
  shot.updatedAt=new Date().toISOString();state.ui.selectedAxisId=axisId;
}
function applyCreativeChoiceMutable(state,axisId,optionId,scope=state.ui.editScope,{select=true}={}){
  const axis=CREATIVE_AXIS_MAP.get(axisId),option=optionFor(axisId,optionId);if(!axis||!option)return false;const shot=activeShot(state);ensureCreativeState(shot);
  const applyEndpoint=(endpoint,patch)=>{shot[endpoint].choices[axisId]=optionId;for(const [numericAxisId,value] of Object.entries(patch||{}))applyAxisMutable(state,numericAxisId,value,endpoint);};
  if(scope==="start"||scope==="both")applyEndpoint("start",option.start);if(scope==="end"||scope==="both")applyEndpoint("end",option.end);
  shot.updatedAt=new Date().toISOString();if(select)state.ui.selectedCreativeAxisId=axisId;return true;
}
function pickCreativeOption(pool,current,rng,{near=false,avoid=null}={}){
  if(!pool.length)return null;if(pool.length===1)return pool[0];const currentIndex=Math.max(0,pool.findIndex(option=>option.id===current));
  let candidates=pool.filter(option=>option.id!==avoid&&option.id!==current);if(!candidates.length)candidates=pool.filter(option=>option.id!==avoid);if(!candidates.length)candidates=pool;
  if(near){const adjacent=[pool[currentIndex-1],pool[currentIndex+1]].filter(option=>option&&option.id!==avoid);if(adjacent.length)candidates=adjacent;}
  return candidates[Math.floor(rng()*candidates.length)]||pool[0];
}
function clipEnd(clip){return clip.startFrame+clip.durationFrames;}
function timelineDuration(state){return Math.max(state.timeline.outFrame||0,...Object.values(state.timeline.clips).map(clipEnd),1);}
function videoTrack(state,trackId){return state.timeline.tracks[trackId]?.type==="video";}
function compatibleTrack(state,trackId,type){const track=state.timeline.tracks[trackId];return Boolean(track&&(type==="shot"?track.type==="video":type==="audio"?track.type==="audio":track.type==="fx"));}
function defaultShotTemplate(id=uid("shot"),name="New Shot"){
  const state=createDefaultState(),defaults=state.shots.byId[state.shots.activeShotId];
  const shot=deepClone(defaults);shot.id=id;shot.name=name;shot.variant=1;shot.seed=Math.abs([...id].reduce((n,c)=>((n*31)+c.charCodeAt(0))|0,43001));shot.updatedAt=new Date().toISOString();return shot;
}
function shotFromPreset(preset,id=uid("shot")){
  const shot=defaultShotTemplate(id,preset.title);shot.family=preset.family;shot.presetId=preset.id;shot.durationFrames=preset.duration;
  for(const axis of AXES){if(preset.start[axis.id]!=null)shot.start.values[axis.id]=clamp(preset.start[axis.id],axis.min,axis.max);if(preset.end[axis.id]!=null)shot.end.values[axis.id]=clamp(preset.end[axis.id],axis.min,axis.max);}
  return shot;
}
function nextTrackEnd(state,trackId){return Object.values(state.timeline.clips).filter(clip=>clip.trackId===trackId).reduce((max,clip)=>Math.max(max,clipEnd(clip)),0);}
function addShotClipMutable(state,shot,{trackId="v1",startFrame=null}={}){
  const start=startFrame==null?nextTrackEnd(state,trackId):Math.max(-10,Math.round(startFrame)),id=uid("clip");
  state.timeline.clips[id]={id,trackId,type:"shot",shotId:shot.id,linked:true,alias:shot.name,startFrame:start,durationFrames:shot.durationFrames,sourceInFrame:0,sourceOutFrame:shot.durationFrames,opacity:1,blendMode:"normal"};
  state.timeline.selectedClipId=id;state.timeline.selectedTrackId=trackId;state.timeline.playheadFrame=start;state.playback.frame=start;state.timeline.outFrame=Math.max(state.timeline.outFrame,clipEnd(state.timeline.clips[id]));state.timeline.durationFrames=timelineDuration(state);return id;
}
function snapFrame(state,value,ignoreClipId=null){
  let frame=Math.max(-10,Math.round(value));if(!state.timeline.snapEnabled)return frame;const candidates=[-10,0,state.timeline.inFrame,state.timeline.outFrame,...(state.timeline.markers||[]).map(marker=>marker.frame)];
  for(const clip of Object.values(state.timeline.clips)){if(clip.id===ignoreClipId)continue;candidates.push(clip.startFrame,clipEnd(clip));}
  let best=frame,distance=3;for(const candidate of candidates){const d=Math.abs(candidate-frame);if(d<distance){best=candidate;distance=d;}}return best;
}

export function registerCommands(bus){
  const {store,history,persistence,sync,toast}=bus.context;
  const validTool=tool=>["select","translate","rotate","scale","pivot"].includes(tool)?tool:"select";
  const validSpace=space=>space==="local"?"local":"world";
  const validMode=mode=>["scene","shot","calibrate"].includes(mode)?mode:"scene";
  const finite3=(value,fallback=[0,0,0])=>Array.isArray(value)&&value.length>=3?value.slice(0,3).map((n,i)=>Number.isFinite(Number(n))?Number(n):fallback[i]):[...fallback];
  const safeTransform=(value,fallback=DEFAULT_TRANSFORM)=>({position:finite3(value?.position,fallback.position),rotation:finite3(value?.rotation,fallback.rotation),scale:finite3(value?.scale,fallback.scale).map((n,i)=>Math.max(.000001,Math.abs(Number(n)||fallback.scale[i]||1)))});
  const sessionTime=()=>new Date().toISOString();
  const applyAssetMutable=(state,asset,node=null)=>{
    if(!asset?.id||!asset.type)return;
    const normalized={semanticType:asset.type,fileName:asset.name||null,bytes:Number(asset.size??asset.bytes)||0,diagnostics:[],status:"ready",source:"indexeddb",...asset};
    normalized.size=Number(normalized.size??normalized.bytes)||0;normalized.bytes=Number(normalized.bytes??normalized.size)||0;normalized.diagnostics=Array.isArray(normalized.diagnostics)?normalized.diagnostics:[];
    state.assets.byId[normalized.id]=normalized;
    const defaults=createDefaultState();
    if(normalized.type==="hero"){
      const old=state.assets.heroId;state.assets.heroId=normalized.id;
      state.scene.nodes["hero-proxy"]={...defaults.scene.nodes["hero-proxy"],assetId:normalized.id,name:`Hero · ${normalized.name}`,visible:true,locked:false,transformLocks:structuredClone(DEFAULT_TRANSFORM_LOCKS),baseTransform:structuredClone(DEFAULT_TRANSFORM),correction:correctionDefaultsForType("hero")};
      if(old&&old!=="hero-proxy"&&old!==normalized.id)delete state.assets.byId[old];state.ui.selectedNodeId="hero-proxy";state.ui.viewportEditMode="calibrate";
    }else if(normalized.type==="environment"){
      const old=state.assets.environmentId;state.assets.environmentId=normalized.id;
      state.scene.nodes["environment-proxy"]={...defaults.scene.nodes["environment-proxy"],assetId:normalized.id,name:`Environment · ${normalized.name}`,visible:true,locked:false,transformLocks:structuredClone(DEFAULT_TRANSFORM_LOCKS),baseTransform:structuredClone(DEFAULT_TRANSFORM),correction:correctionDefaultsForType("environment")};
      if(old&&old!=="environment-proxy"&&old!==normalized.id)delete state.assets.byId[old];state.ui.selectedNodeId="environment-proxy";state.ui.viewportEditMode="scene";
    }else if(normalized.type==="hdri"){
      const old=state.assets.hdriId;state.assets.hdriId=normalized.id;if(old&&old!==normalized.id)delete state.assets.byId[old];
    }else if(normalized.type==="prop"){
      const nodeId=node?.id||normalized.nodeId||`prop-${normalized.id}`;normalized.nodeId=nodeId;state.assets.secondaryIds=[...new Set([...(state.assets.secondaryIds||[]),normalized.id])];
      state.scene.nodes[nodeId]={id:nodeId,name:node?.name||`Prop · ${normalized.name}`,type:"prop",assetId:normalized.id,parentId:null,visible:node?.visible!==false,locked:false,transformLocks:{...DEFAULT_TRANSFORM_LOCKS,...(node?.transformLocks||{})},baseTransform:safeTransform(node?.baseTransform),correction:{...correctionDefaultsForType("prop"),...(node?.correction||{})},helpers:{bounds:true,pivot:false,...(node?.helpers||{})}};state.ui.selectedNodeId=nodeId;state.ui.viewportEditMode="scene";
    }else if(normalized.type==="audio")state.assets.audioIds=[...new Set([...(state.assets.audioIds||[]),normalized.id])];
  };

  bus.register("history.undo",()=>store.undo());bus.register("history.redo",()=>store.redo());
  bus.register("gesture.begin",({label})=>store.beginGesture(label));bus.register("gesture.end",()=>store.endGesture());bus.register("gesture.cancel",()=>store.cancelGesture());
  bus.register("ui.setScope",({scope})=>store.transient("Edit scope",state=>state.ui.editScope=["start","both","end"].includes(scope)?scope:"both",{persist:true,broadcast:true}));
  bus.register("ui.toggleAdvanced",({value})=>store.transient("Advanced mode",state=>state.ui.advanced=Boolean(value),{persist:true,broadcast:true}));
  bus.register("ui.setViewportTool",({tool})=>store.transient("Viewport tool",state=>{const next=validTool(tool),node=state.scene.nodes[state.ui.selectedNodeId];if(next==="pivot"&&node?.type==="hero"&&state.ui.viewportEditMode==="shot")state.ui.viewportEditMode="calibrate";state.ui.viewportTool=next;},{persist:true,broadcast:false}));
  bus.register("ui.setViewportSpace",({space})=>store.transient("Viewport space",state=>state.ui.viewportSpace=validSpace(space),{persist:true,broadcast:false}));
  bus.register("ui.setViewportEditMode",({mode})=>store.transient("Viewport edit mode",state=>{const node=state.scene.nodes[state.ui.selectedNodeId],next=validMode(mode);state.ui.viewportEditMode=node?.type==="hero"?(next==="shot"?"shot":"calibrate"):"scene";if(state.ui.viewportEditMode==="shot"&&state.ui.viewportTool==="pivot")state.ui.viewportTool="select";},{persist:true,broadcast:false}));
  bus.register("ui.setViewportSnap",({enabled,field,value}={})=>store.transient("Viewport snap",state=>{if(enabled!=null)state.ui.viewportSnapEnabled=Boolean(enabled);state.ui.viewportSnap??={position:.1,rotationDeg:15,scale:.1,pivot:.1};if(field&&field in state.ui.viewportSnap&&Number.isFinite(Number(value)))state.ui.viewportSnap[field]=Math.max(.0001,Number(value));},{persist:true,broadcast:false}));
  bus.register("ui.setViewportCameraMode",({mode})=>store.transient("Viewport camera mode",state=>state.scene.viewportCameraMode=mode==="shot"?"shot":"editor",{persist:true,broadcast:false}));
  bus.register("ui.setTimelineMonitorMode",({mode})=>store.transient("Timeline monitor mode",state=>state.ui.timelineMonitorMode=mode==="viewport"?"viewport":"player",{persist:true,broadcast:false}));
  bus.register("ui.setAssetBusy",({value})=>store.transient("Asset busy",state=>state.ui.assetBusy=Boolean(value),{persist:false,broadcast:false}));
  bus.register("ui.selectNode",({nodeId})=>store.transient("Select node",state=>{if(!state.scene.nodes[nodeId])return;state.ui.selectedNodeId=nodeId;const node=state.scene.nodes[nodeId];if(node.type!=="hero")state.ui.viewportEditMode="scene";},{persist:true,broadcast:false}));
  bus.register("ui.selectCreativeAxis",({axisId})=>store.transient("Select creative axis",state=>state.ui.selectedCreativeAxisId=axisId,{persist:true,broadcast:false}));
  bus.register("ui.openProject",({open=true})=>store.transient("Project dialog",state=>state.ui.projectDialogOpen=open));
  bus.register("ui.setTimelineTool",({tool})=>store.transient("Timeline tool",state=>state.ui.timelineTool=["select","blade","slip"].includes(tool)?tool:"select",{persist:true,broadcast:false}));

  bus.register("project.rename",({name})=>store.commit("Rename project",state=>state.meta.name=(name||"Untitled Project").trim()||"Untitled Project"));
  bus.register("project.reset",async()=>{await persistence.clear({assets:true});const next=createDefaultState();history.clear();store.replace("Reset project",next,{history:false,persist:true,broadcast:true});toast?.("PROJECT RESET · V44");});

  bus.register("asset.stageImport",({session})=>store.transient("Stage asset import",state=>{state.assets.importSession={id:session?.id||uid("import"),assetId:session?.assetId||null,type:session?.type||null,nodeId:session?.nodeId||null,name:session?.name||"Asset",status:"staging",previousAssetId:session?.previousAssetId||null,diagnostics:[],message:"Parsing in isolated scene",startedAt:sessionTime()};state.ui.assetBusy=true;},{persist:false,broadcast:false}));
  bus.register("asset.validateStagedImport",({sessionId,diagnostics=[],meta={}})=>store.transient("Validate staged asset",state=>{const session=state.assets.importSession;if(!session||(sessionId&&session.id!==sessionId))return;session.status="validated";session.diagnostics=Array.isArray(diagnostics)?diagnostics:[];session.meta=meta;session.message="Validated · ready to commit";},{persist:false,broadcast:false}));
  bus.register("asset.failImport",({sessionId,error,diagnostics=[]}={})=>store.transient("Asset import failed",state=>{const session=state.assets.importSession;if(session&&(!sessionId||session.id===sessionId)){session.status="error";session.message=String(error?.message||error||"Import failed");session.diagnostics=[...(session.diagnostics||[]),...(diagnostics||[])];}state.ui.assetBusy=false;},{persist:false,broadcast:false}));
  bus.register("asset.cancelImport",({sessionId}={})=>store.transient("Cancel asset import",state=>{if(!sessionId||state.assets.importSession?.id===sessionId)state.assets.importSession=null;state.ui.assetBusy=false;},{persist:false,broadcast:false}));
  bus.register("asset.commitImport",({asset,node,sessionId}={})=>{const session=store.get().assets.importSession;if(sessionId&&session?.id!==sessionId)return false;store.transient("Close asset staging",state=>{state.assets.importSession=null;state.ui.assetBusy=false;},{persist:false,broadcast:false});return store.commit(`Import ${asset?.type||"asset"}`,state=>applyAssetMutable(state,asset,node));});
  bus.register("asset.register",({asset,node})=>store.commit(`Register ${asset?.type||"asset"} asset`,state=>applyAssetMutable(state,asset,node)));
  bus.register("asset.markMissing",({assetId,nodeId,error,message}={})=>store.commit("Mark asset unavailable",state=>{const asset=state.assets.byId[assetId];if(asset){asset.status="missing";asset.diagnostics=[...(asset.diagnostics||[]),{level:"error",code:"BINARY_MISSING",message:String(message||error||"Binary data missing")}];asset.updatedAt=sessionTime();}if(nodeId&&state.scene.nodes[nodeId])state.scene.nodes[nodeId].missing=true;}));
  bus.register("asset.remove",({assetId,nodeId})=>store.commit("Remove scene asset",state=>{
    const asset=state.assets.byId[assetId];if(!asset)return;const defaults=createDefaultState();
    if(asset.type==="hero"){state.assets.heroId="hero-proxy";state.scene.nodes["hero-proxy"]=structuredClone(defaults.scene.nodes["hero-proxy"]);state.ui.selectedNodeId="hero-proxy";state.ui.viewportEditMode="shot";}
    else if(asset.type==="environment"){state.assets.environmentId="environment-proxy";state.scene.nodes["environment-proxy"]=structuredClone(defaults.scene.nodes["environment-proxy"]);state.ui.selectedNodeId="environment-proxy";state.ui.viewportEditMode="scene";}
    else if(asset.type==="hdri"){state.assets.hdriId=null;state.scene.environment.backgroundVisible=false;}
    else if(asset.type==="prop"){state.assets.secondaryIds=(state.assets.secondaryIds||[]).filter(id=>id!==assetId);const resolved=nodeId||asset.nodeId;if(resolved)delete state.scene.nodes[resolved];if(state.ui.selectedNodeId===resolved)state.ui.selectedNodeId="hero-proxy";}
    else if(asset.type==="audio"){state.assets.audioIds=(state.assets.audioIds||[]).filter(id=>id!==assetId);for(const [id,clip] of Object.entries(state.timeline.clips))if(clip.assetId===assetId)delete state.timeline.clips[id];}
    delete state.assets.byId[assetId];state.timeline.durationFrames=timelineDuration(state);
  }));

  bus.register("scene.setNodeTransform",({nodeId,transform,gesture=false})=>{const mutate=state=>{const node=state.scene.nodes[nodeId];if(!node||node.locked)return;const current=safeTransform(node.baseTransform),next=safeTransform(transform,current),locks={...DEFAULT_TRANSFORM_LOCKS,...node.transformLocks};node.baseTransform={position:locks.position?current.position:next.position,rotation:locks.rotation?current.rotation:next.rotation,scale:locks.scale?current.scale:next.scale};};return gesture?store.updateGesture("Transform scene node",mutate):store.commit("Transform scene node",mutate);});
  bus.register("scene.setNodeCorrection",({nodeId,field,value,gesture=false})=>{const mutate=state=>{const node=state.scene.nodes[nodeId];if(!node||node.locked)return;node.correction??=correctionDefaultsForType(node.type);node.transformLocks={...DEFAULT_TRANSFORM_LOCKS,...node.transformLocks};if(field==="pivot"&&(node.transformLocks.pivot||node.transformLocks.position))return;if(field==="rotation"&&node.transformLocks.rotation)return;if(field==="scale"&&node.transformLocks.scale)return;if(["pivot","rotation","scale"].includes(field))node.correction[field]=finite3(value,node.correction[field]||correctionDefaultsForType(node.type)[field]);else node.correction[field]=value;if(node.type==="hero"){node.correction.autoNormalize=true;node.correction.normalizeMode="camera";}if(node.type==="environment"){node.correction.autoNormalize=false;node.correction.normalizeMode="native";}};return gesture?store.updateGesture("Correct scene node",mutate):store.commit("Correct scene node",mutate);});
  bus.register("scene.setNodePivotCompensated",({nodeId,pivot,baseTransform,gesture=false})=>{const mutate=state=>{const node=state.scene.nodes[nodeId];if(!node||node.locked)return;node.transformLocks={...DEFAULT_TRANSFORM_LOCKS,...node.transformLocks};if(node.transformLocks.pivot||node.transformLocks.position)return;node.correction??=correctionDefaultsForType(node.type);node.correction.pivot=finite3(pivot,node.correction.pivot);node.baseTransform=safeTransform(baseTransform,node.baseTransform);if(node.type==="hero"){node.correction.autoNormalize=true;node.correction.normalizeMode="camera";}if(node.type==="environment"){node.correction.autoNormalize=false;node.correction.normalizeMode="native";}};return gesture?store.updateGesture("Move pivot without moving geometry",mutate):store.commit("Move pivot without moving geometry",mutate);});
  bus.register("scene.applyPivotPreset",({nodeId,preset,pivot,baseTransform})=>store.commit(`Pivot preset · ${preset||"custom"}`,state=>{const node=state.scene.nodes[nodeId];if(!node||node.locked||node.transformLocks?.pivot||node.transformLocks?.position)return;node.correction.pivot=finite3(pivot,node.correction.pivot);node.baseTransform=safeTransform(baseTransform,node.baseTransform);}));
  bus.register("scene.groundNode",({nodeId,transform,positionY})=>store.commit("Ground scene node",state=>{const node=state.scene.nodes[nodeId];if(!node||node.locked||node.transformLocks?.position)return;const next=safeTransform(transform||node.baseTransform,node.baseTransform);if(Number.isFinite(Number(positionY)))next.position[1]=Number(positionY);node.baseTransform=next;}));
  bus.register("scene.resetNodeTransform",({nodeId})=>store.commit("Reset node transform",state=>{const node=state.scene.nodes[nodeId];if(!node||node.locked)return;node.baseTransform=structuredClone(DEFAULT_TRANSFORM);}));
  bus.register("scene.resetNodeCorrection",({nodeId})=>store.commit("Reset node correction",state=>{const node=state.scene.nodes[nodeId];if(node&&!node.locked)node.correction=correctionDefaultsForType(node.type);}));
  bus.register("scene.setNodeVisible",({nodeId,value})=>store.commit("Toggle node visibility",state=>{const node=state.scene.nodes[nodeId];if(node)node.visible=Boolean(value);}));
  bus.register("scene.setNodeLocked",({nodeId,value})=>store.commit("Lock scene node",state=>{const node=state.scene.nodes[nodeId];if(node)node.locked=value==null?!node.locked:Boolean(value);}));
  bus.register("scene.setTransformChannelLock",({nodeId,channel,value})=>store.commit(`Lock ${channel}`,state=>{const node=state.scene.nodes[nodeId];if(!node||!["position","rotation","scale","pivot"].includes(channel))return;node.transformLocks={...DEFAULT_TRANSFORM_LOCKS,...node.transformLocks,[channel]:value==null?!node.transformLocks?.[channel]:Boolean(value)};}));
  bus.register("scene.setEnvironment",({field,value})=>store.commit("Environment setting",state=>state.scene.environment[field]=value));
  bus.register("scene.setRenderer",({field,value})=>store.commit("Renderer setting",state=>state.scene.rendererSettings[field]=value));
  bus.register("scene.setEditorCamera",({camera})=>store.transient("Editor camera",state=>state.scene.editorCamera={...state.scene.editorCamera,...camera},{persist:true,broadcast:false}));
  bus.register("scene.toggleGrid",()=>store.transient("Viewport grid",state=>state.scene.showGrid=!state.scene.showGrid,{persist:true,broadcast:false}));bus.register("scene.toggleHelpers",()=>store.transient("Viewport helpers",state=>state.scene.showHelpers=!state.scene.showHelpers,{persist:true,broadcast:false}));

  bus.register("shot.select",({shotId})=>store.transient("Select shot",state=>{if(!state.shots.byId[shotId])return;state.shots.activeShotId=shotId;state.playback.frame=0;state.playback.playing=false;},{persist:true,broadcast:true}));
  bus.register("shot.duplicate",()=>store.commit("Duplicate shot",state=>{const source=activeShot(state),id=uid("shot"),copy=deepClone(source);copy.id=id;copy.name=`${source.name.replace(/ · COPY \d+$/,'')} · COPY ${state.shots.order.length}`;copy.variant=1;copy.seed+=state.shots.order.length*101;copy.updatedAt=new Date().toISOString();state.shots.byId[id]=copy;state.shots.order.push(id);state.shots.activeShotId=id;state.playback.frame=0;}));
  bus.register("shot.new",()=>store.commit("New shot",state=>{const shot=defaultShotTemplate(uid("shot"),`Shot ${String(state.shots.order.length+1).padStart(2,"0")}`);state.shots.byId[shot.id]=shot;state.shots.order.push(shot.id);state.shots.activeShotId=shot.id;state.playback.frame=0;}));
  bus.register("shot.delete",({shotId=store.get().shots.activeShotId}={})=>store.commit("Delete shot",state=>{if(state.shots.order.length<=1)return;delete state.shots.byId[shotId];state.shots.order=state.shots.order.filter(id=>id!==shotId);for(const [id,clip] of Object.entries(state.timeline.clips))if(clip.shotId===shotId)delete state.timeline.clips[id];state.shots.activeShotId=state.shots.order[0];state.timeline.selectedClipId=null;state.timeline.durationFrames=timelineDuration(state);}));
  bus.register("shot.setAxis",({axisId,value,scope,gesture=false})=>{const mutate=state=>applyAxisMutable(state,axisId,value,scope);return gesture?store.updateGesture(`Edit ${AXIS_MAP.get(axisId)?.label||axisId}`,mutate):store.commit(`Edit ${AXIS_MAP.get(axisId)?.label||axisId}`,mutate);});
  bus.register("shot.setCreativeChoice",({axisId,optionId,scope})=>store.commit(`Creative axis · ${axisId}`,state=>applyCreativeChoiceMutable(state,axisId,optionId,scope)));
  bus.register("shot.toggleCreativeLock",({axisId})=>store.commit(`Lock creative axis · ${axisId}`,state=>{const shot=activeShot(state),axis=CREATIVE_AXIS_MAP.get(axisId);if(!axis)return;ensureCreativeState(shot);shot.creativeLocks[axisId]=!shot.creativeLocks[axisId];syncNumericLocksFromCreativeLocks(shot);state.ui.selectedCreativeAxisId=axisId;}));
  bus.register("shot.toggleCreativeExclusion",({axisId,optionId})=>store.commit(`Generation pool · ${axisId} · ${optionId}`,state=>{const shot=activeShot(state),axis=CREATIVE_AXIS_MAP.get(axisId),option=optionFor(axisId,optionId);if(!axis||!option)return;ensureCreativeState(shot);const key=exclusionKey(axisId,optionId);if(shot.creativeExclusions[key])delete shot.creativeExclusions[key];else shot.creativeExclusions[key]=true;state.ui.selectedCreativeAxisId=axisId;shot.updatedAt=new Date().toISOString();}));
  bus.register("shot.resetCreativePool",({axisId}={})=>store.commit(axisId?`Reset generation pool · ${axisId}`:"Reset all generation pools",state=>{const shot=activeShot(state);ensureCreativeState(shot);if(axisId){for(const option of CREATIVE_AXIS_MAP.get(axisId)?.options||[])delete shot.creativeExclusions[exclusionKey(axisId,option.id)];state.ui.selectedCreativeAxisId=axisId;}else shot.creativeExclusions={};shot.updatedAt=new Date().toISOString();}));
  bus.register("shot.setDuration",({frames})=>store.commit("Edit shot duration",state=>{const shot=activeShot(state);shot.durationFrames=clamp(Math.round(Number(frames)||72),12,480);state.playback.frame=Math.min(state.playback.frame,shot.durationFrames);}));
  bus.register("shot.setDeltaTarget",({value})=>store.commit("Set delta target",state=>activeShot(state).deltaTarget=clamp(Number(value),.05,.95)));
  bus.register("shot.setFamily",({family})=>store.commit("Select shot family",state=>{activeShot(state).family=family;activeShot(state).presetId=null;}));
  bus.register("shot.applyPreset",({presetId})=>{const preset=PRESET_MAP.get(presetId);if(!preset)return false;return store.commit(`Preset · ${preset.title}`,state=>{const shot=activeShot(state);shot.name=preset.title;shot.family=preset.family;shot.presetId=preset.id;shot.durationFrames=preset.duration;for(const axis of AXES){if(shot.locks[axis.id])continue;if(preset.start[axis.id]!=null)shot.start.values[axis.id]=clamp(preset.start[axis.id],axis.min,axis.max);if(preset.end[axis.id]!=null)shot.end.values[axis.id]=clamp(preset.end[axis.id],axis.min,axis.max);}shot.updatedAt=new Date().toISOString();state.playback.frame=0;state.playback.playing=true;state.playback.lastTick=performance.now();});});
  bus.register("shot.generateVariant",({mode="balanced"})=>store.commit(`Generate ${mode} variant`,state=>{
    const shot=activeShot(state);ensureCreativeState(shot);syncNumericLocksFromCreativeLocks(shot);const target=clamp(Number(shot.deltaTarget??.42),.05,.95),targetFactor=.55+target*1.25;
    const base=mode==="near"?{axisChance:.26,startChance:0,jitter:.018}:mode==="bold"?{axisChance:.72,startChance:.5,jitter:.075}:{axisChance:.48,startChance:.18,jitter:.042};
    const config={axisChance:clamp(base.axisChance*targetFactor,.12,.96),startChance:clamp(base.startChance*targetFactor,0,.82),jitter:base.jitter*targetFactor};
    const rng=seeded(shot.seed+shot.variant*7919+(mode==="bold"?97:mode==="near"?13:41)),eligible=[],blockedNumericAxes=new Set();let creativeChanged=0;
    for(const axis of CREATIVE_AXES){const pool=allowedCreativeOptions(shot,axis);if(shot.creativeLocks[axis.id]||!pool.length){if(!pool.length)for(const numericAxisId of axis.advancedAxes||[])blockedNumericAxes.add(numericAxisId);continue;}eligible.push({axis,pool});if(rng()>config.axisChance)continue;
      if(mode==="near"){const option=pickCreativeOption(pool,shot.end.choices[axis.id],rng,{near:true});if(option&&option.id!==shot.end.choices[axis.id]){applyCreativeChoiceMutable(state,axis.id,option.id,"end",{select:false});creativeChanged++;}}
      else if(mode==="balanced"){if(rng()<config.startChance){const start=pickCreativeOption(pool,shot.start.choices[axis.id],rng,{near:true});if(start&&start.id!==shot.start.choices[axis.id]){applyCreativeChoiceMutable(state,axis.id,start.id,"start",{select:false});creativeChanged++;}}const end=pickCreativeOption(pool,shot.end.choices[axis.id],rng,{avoid:shot.start.choices[axis.id]});if(end&&end.id!==shot.end.choices[axis.id]){applyCreativeChoiceMutable(state,axis.id,end.id,"end",{select:false});creativeChanged++;}}
      else{const start=pickCreativeOption(pool,shot.start.choices[axis.id],rng);if(start&&start.id!==shot.start.choices[axis.id]){applyCreativeChoiceMutable(state,axis.id,start.id,"start",{select:false});creativeChanged++;}const end=pickCreativeOption(pool,shot.end.choices[axis.id],rng,{avoid:start?.id||shot.start.choices[axis.id]});if(end&&end.id!==shot.end.choices[axis.id]){applyCreativeChoiceMutable(state,axis.id,end.id,"end",{select:false});creativeChanged++;}}
    }
    if(!creativeChanged&&eligible.length){const targetAxis=eligible[Math.floor(rng()*eligible.length)],scope=mode==="bold"?"both":"end",current=scope==="both"?shot.start.choices[targetAxis.axis.id]:shot.end.choices[targetAxis.axis.id],option=pickCreativeOption(targetAxis.pool,current,rng,{near:mode==="near"});if(option)applyCreativeChoiceMutable(state,targetAxis.axis.id,option.id,scope,{select:false});}
    for(const axis of AXES){if(shot.locks[axis.id]||blockedNumericAxes.has(axis.id)||rng()>.30*targetFactor)continue;const range=axis.max-axis.min,endDelta=(rng()-.5)*2*range*config.jitter;shot.end.values[axis.id]=clamp(shot.end.values[axis.id]+endDelta,axis.min,axis.max);if(mode==="bold"&&rng()>.55)shot.start.values[axis.id]=clamp(shot.start.values[axis.id]+(rng()-.5)*range*config.jitter*.55,axis.min,axis.max);}
    shot.variant+=1;shot.variantMode=mode;shot.presetId=null;shot.name=`${shot.name.replace(/ · V\d+$/,'')} · V${String(shot.variant).padStart(2,'0')}`;shot.updatedAt=new Date().toISOString();state.playback.frame=0;state.playback.playing=true;state.playback.lastTick=performance.now();
  }));
  bus.register("shot.reset",()=>store.commit("Reset active shot",state=>{const id=activeShot(state).id,replacement=defaultShotTemplate(id,"Silent Authority");state.shots.byId[id]=replacement;state.playback.frame=0;state.playback.playing=false;}));
  bus.register("shot.addToTimeline",({trackId="v1"}={})=>store.commit("Add or update shot in timeline",state=>{const shot=activeShot(state),selected=state.timeline.clips[state.timeline.selectedClipId];if(selected?.type==="shot"&&selected.linked&&selected.shotId===shot.id){selected.alias=shot.name;selected.sourceOutFrame=Math.min(shot.durationFrames,selected.sourceInFrame+selected.durationFrames);toast?.("LINKED SHOT UPDATED");return;}addShotClipMutable(state,shot,{trackId});toast?.("SHOT ADDED TO TIMELINE");}));

  bus.register("playback.toggle",()=>store.transient("Toggle playback",state=>{state.playback.playing=!state.playback.playing;state.playback.lastTick=performance.now();}));
  bus.register("playback.setLoop",({value})=>store.transient("Loop",state=>{state.playback.loop=Boolean(value);state.timeline.loop=Boolean(value);},{persist:true,broadcast:true}));
  bus.register("playback.seek",({frame})=>store.transient("Seek",state=>{const timeline=state.ui.activeWorkspace==="timeline",max=timeline?timelineDuration(state):activeShot(state).durationFrames,min=timeline?-10:0,safe=clamp(Math.round(Number(frame)||0),min,max);state.playback.playing=false;state.playback.frame=safe;if(timeline)state.timeline.playheadFrame=safe;},{persist:true,broadcast:false}));
  bus.register("playback.jumpStart",()=>{const state=store.get();return bus.dispatch("playback.seek",{frame:state.ui.activeWorkspace==="timeline"?state.timeline.inFrame:0});});
  bus.register("playback.jumpEnd",()=>{const state=store.get(),max=state.ui.activeWorkspace==="timeline"?state.timeline.outFrame:activeShot(state).durationFrames;return bus.dispatch("playback.seek",{frame:max});});

  bus.register("timeline.selectClip",({clipId})=>store.transient("Select clip",state=>{state.timeline.selectedClipId=clipId;const clip=state.timeline.clips[clipId];if(clip){state.timeline.selectedTrackId=clip.trackId;state.timeline.playheadFrame=clip.startFrame;state.playback.frame=clip.startFrame;if(clip.type==="shot"&&clip.shotId)state.shots.activeShotId=clip.shotId;}},{persist:true,broadcast:false}));
  bus.register("timeline.setPlayhead",({frame})=>store.transient("Timeline playhead",state=>{const safe=clamp(Math.round(frame),-10,timelineDuration(state));state.timeline.playheadFrame=safe;state.playback.frame=safe;state.playback.playing=false;},{persist:true,broadcast:false}));
  bus.register("timeline.moveClip",({clipId,startFrame,trackId,gesture=false})=>{const mutate=state=>{const clip=state.timeline.clips[clipId];if(!clip)return;clip.startFrame=snapFrame(state,startFrame,clipId);if(trackId&&compatibleTrack(state,trackId,clip.type))clip.trackId=trackId;state.timeline.outFrame=Math.max(state.timeline.outFrame,clipEnd(clip));state.timeline.durationFrames=timelineDuration(state);};return gesture?store.updateGesture("Move timeline clip",mutate):store.commit("Move timeline clip",mutate);});
  bus.register("timeline.trimClip",({clipId,durationFrames,gesture=false})=>{const mutate=state=>{const clip=state.timeline.clips[clipId];if(!clip)return;clip.durationFrames=Math.max(1,Math.round(durationFrames));clip.sourceOutFrame=(clip.sourceInFrame||0)+clip.durationFrames;state.timeline.outFrame=Math.max(state.timeline.outFrame,clipEnd(clip));state.timeline.durationFrames=timelineDuration(state);};return gesture?store.updateGesture("Trim timeline clip",mutate):store.commit("Trim timeline clip",mutate);});
  bus.register("timeline.trimClipSide",({clipId,side,startFrame,durationFrames,sourceInFrame,gesture=false})=>{const mutate=state=>{const clip=state.timeline.clips[clipId];if(!clip)return;if(side==="left"){clip.startFrame=Math.max(-10,Math.round(startFrame));clip.durationFrames=Math.max(1,Math.round(durationFrames));clip.sourceInFrame=Math.max(0,Math.round(sourceInFrame));}else{clip.durationFrames=Math.max(1,Math.round(durationFrames));}clip.sourceOutFrame=(clip.sourceInFrame||0)+clip.durationFrames;state.timeline.durationFrames=timelineDuration(state);};return gesture?store.updateGesture(`Trim ${side} clip`,mutate):store.commit(`Trim ${side} clip`,mutate);});
  bus.register("timeline.slipClip",({clipId,sourceInFrame,gesture=false})=>{const mutate=state=>{const clip=state.timeline.clips[clipId];if(!clip||clip.type!=="shot")return;const shot=state.shots.byId[clip.shotId],max=Math.max(0,(shot?.durationFrames||clip.durationFrames)-clip.durationFrames);clip.sourceInFrame=clamp(Math.round(sourceInFrame),0,max);clip.sourceOutFrame=clip.sourceInFrame+clip.durationFrames;};return gesture?store.updateGesture("Slip timeline clip",mutate):store.commit("Slip timeline clip",mutate);});
  bus.register("timeline.splitClip",({clipId,frame})=>store.commit("Blade split",state=>{const clip=state.timeline.clips[clipId];if(!clip)return;const cut=clamp(Math.round(frame),clip.startFrame+1,clipEnd(clip)-1),leftDuration=cut-clip.startFrame,right=deepClone(clip),rightId=uid("clip");clip.durationFrames=leftDuration;clip.sourceOutFrame=(clip.sourceInFrame||0)+leftDuration;right.id=rightId;right.startFrame=cut;right.durationFrames=Math.max(1,clipEnd(right)-cut);right.sourceInFrame=(clip.sourceInFrame||0)+leftDuration;right.sourceOutFrame=right.sourceInFrame+right.durationFrames;right.alias=`${clip.alias} B`;state.timeline.clips[rightId]=right;state.timeline.selectedClipId=rightId;state.timeline.playheadFrame=cut;}));
  bus.register("timeline.deleteClip",({clipId})=>store.commit("Delete timeline clip",state=>{delete state.timeline.clips[clipId];state.timeline.selectedClipId=null;state.timeline.durationFrames=timelineDuration(state);}));
  bus.register("timeline.toggleSnap",()=>store.transient("Timeline snap",state=>state.timeline.snapEnabled=!state.timeline.snapEnabled,{persist:true,broadcast:true}));
  bus.register("timeline.setZoom",({value})=>store.transient("Timeline zoom",state=>state.timeline.zoom=clamp(Number(value),2,14),{persist:true,broadcast:false}));
  bus.register("timeline.toggleTrack",({trackId,field})=>store.commit(`Track ${field}`,state=>{const track=state.timeline.tracks[trackId];if(track&&["locked","muted","visible"].includes(field))track[field]=!track[field];}));
  bus.register("timeline.addMarker",({frame,label="MARK"}={})=>store.commit("Add timeline marker",state=>{state.timeline.markers??=[];state.timeline.markers.push({id:uid("marker"),frame:clamp(Math.round(frame??state.timeline.playheadFrame),-10,timelineDuration(state)),label:String(label||"MARK")});}));
  bus.register("timeline.deleteMarker",({markerId})=>store.commit("Delete timeline marker",state=>state.timeline.markers=(state.timeline.markers||[]).filter(marker=>marker.id!==markerId)));
  bus.register("timeline.makeUnique",({clipId})=>store.commit("Make clip unique",state=>{const clip=state.timeline.clips[clipId];if(!clip||clip.type!=="shot"||!clip.shotId)return;const source=state.shots.byId[clip.shotId];if(!source)return;const shot=deepClone(source),id=uid("shot");shot.id=id;shot.name=`${source.name} · UNIQUE`;shot.updatedAt=new Date().toISOString();state.shots.byId[id]=shot;state.shots.order.push(id);clip.shotId=id;clip.linked=false;clip.alias=shot.name;state.shots.activeShotId=id;}));
  bus.register("timeline.addFx",({effect="flash",trackId="gfx",durationFrames=12,startFrame}={})=>store.commit("Add FX clip",state=>{const id=uid("clip"),start=startFrame??state.timeline.playheadFrame;state.timeline.clips[id]={id,trackId,type:"fx",effect,alias:effect.toUpperCase(),startFrame:Math.max(-10,Math.round(start)),durationFrames:Math.max(1,Math.round(durationFrames)),sourceInFrame:0,sourceOutFrame:durationFrames,opacity:1};state.timeline.selectedClipId=id;state.timeline.durationFrames=timelineDuration(state);}));
  bus.register("timeline.addAudio",({assetId,trackId="a1",durationFrames,startFrame=0}={})=>store.commit("Add audio clip",state=>{if(!state.assets.byId[assetId]||!compatibleTrack(state,trackId,"audio"))return;const asset=state.assets.byId[assetId],id=uid("clip"),duration=Math.max(1,Math.round(durationFrames||asset.meta?.durationFrames||state.settings.fps*4));state.timeline.clips[id]={id,trackId,type:"audio",assetId,alias:asset.name,startFrame:Math.max(-10,Math.round(startFrame)),durationFrames:duration,sourceInFrame:0,sourceOutFrame:duration,volume:1,fadeInFrames:0,fadeOutFrames:0};state.timeline.selectedClipId=id;state.timeline.selectedTrackId=trackId;state.timeline.durationFrames=timelineDuration(state);}));
  bus.register("timeline.applySequencePreset",({presetId})=>{const preset=SEQUENCE_PRESET_MAP.get(presetId);if(!preset)return false;return store.commit(`Sequence preset · ${preset.label}`,state=>{for(const [id,clip] of Object.entries(state.timeline.clips))if(clip.type==="shot")delete state.timeline.clips[id];let cursor=0,lastShotId=null;for(const presetId of preset.shots){const shotPreset=PRESET_MAP.get(presetId);if(!shotPreset)continue;const shot=shotFromPreset(shotPreset);state.shots.byId[shot.id]=shot;state.shots.order.push(shot.id);addShotClipMutable(state,shot,{trackId:"v1",startFrame:cursor});cursor+=shot.durationFrames;lastShotId=shot.id;}if(lastShotId)state.shots.activeShotId=lastShotId;state.timeline.sequencePresetId=preset.id;state.timeline.playheadFrame=0;state.playback.frame=0;state.timeline.outFrame=Math.max(cursor,1);state.timeline.durationFrames=timelineDuration(state);});});
  bus.register("timeline.clearShots",()=>store.commit("Clear sequence shots",state=>{for(const [id,clip] of Object.entries(state.timeline.clips))if(clip.type==="shot")delete state.timeline.clips[id];state.timeline.selectedClipId=null;state.timeline.playheadFrame=0;state.timeline.durationFrames=timelineDuration(state);state.timeline.sequencePresetId="empty";}));
  bus.register("timeline.updateSelected",({field,value})=>store.commit("Edit selected clip",state=>{const clip=state.timeline.clips[state.timeline.selectedClipId];if(!clip)return;if(field==="alias")clip.alias=String(value||"Clip");if(field==="startFrame")clip.startFrame=Math.max(-10,Math.round(Number(value)||0));if(field==="durationFrames"){clip.durationFrames=Math.max(1,Math.round(Number(value)||1));clip.sourceOutFrame=(clip.sourceInFrame||0)+clip.durationFrames;}if(field==="trackId"&&compatibleTrack(state,value,clip.type))clip.trackId=value;if(field==="sourceInFrame"&&clip.type==="shot"){const shot=state.shots.byId[clip.shotId],max=Math.max(0,(shot?.durationFrames||clip.durationFrames)-clip.durationFrames);clip.sourceInFrame=clamp(Math.round(Number(value)||0),0,max);clip.sourceOutFrame=clip.sourceInFrame+clip.durationFrames;}if(field==="volume"&&clip.type==="audio")clip.volume=clamp(Number(value),0,1);state.timeline.durationFrames=timelineDuration(state);}));
  return bus;
}
